In [4]:
#ques1
import numpy as np
x=np.zeros(10)
x[4]=1
print(x)


[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


In [6]:
#ques2
arr=np.arange(10,49)
print(arr)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48]


In [8]:
#ques3
import numpy as np
x =  np.arange(0, 9).reshape(3,3)
print(x)


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [16]:
#ques4
arr=np.random.randint(100,size=(10,10))
print(arr)
print('Max of arr:' ,np.min(arr))
print('Min of arr:' ,np.max(arr))

[[ 0 55 80 95 24  1 59 70 75  7]
 [61 68  3 25 45 50 78 29 31 38]
 [83 43  9 23 59 74  3 33 63 69]
 [37 51 32 24 57 35 83 24 65 84]
 [ 1 46 31 51  3 38 77  8 51 96]
 [59 92 98 67 13 37 10 93 37  5]
 [35 41 52 73 46  3 48 63 36 41]
 [19 29 91 35  0 77 90 31 93 41]
 [39 35 22 83 55 44 89 74  4 65]
 [95 71 51 51 47 77 16 22  5 52]]
Max of arr: 0
Min of arr: 98


In [20]:
#ques6
y = np.random.random(30)
x = y.mean()
print(x)

0.5619172861097584


In [21]:
#ques4
x = np.nonzero([1,2,0,0,4,0])
print(x)


(array([0, 1, 4], dtype=int64),)
